[features]
seeds = true
skip-lint = false

[workspace]
members = ["."]

[programs.localnet]
trashure_escrow = "3jyAWteaJfAmPFcn4kHSKJZCGt41nu4ZaDchvBsDFJdi"

[programs.devnet]
trashure_escrow = "3jyAWteaJfAmPFcn4kHSKJZCGt41nu4ZaDchvBsDFJdi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
